import { PageTransition } from '../components/PageTransition';
import { AnimatedSection, AnimatedItem } from '../components/AnimatedSection';
import { DepthElement } from '../components/DepthElement';
import { motion, useScroll, useTransform, AnimatePresence } from 'motion/react';
import { useRef, useState } from 'react';
import { BrainCircuit, ThumbsUp, CheckSquare, Database, Target, Globe, ChevronDown } from 'lucide-react';

export default function Services() {
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const trainingServices = [
    { 
      id: "reasoning-verified", 
      title: "Reasoning Verification", 
      desc: "Scientific experts structure multi-step logic paths for LLMs to learn optimal reasoning patterns across physical sciences and abstract physics.",
      details: "Our workflow includes step-by-step annotation of complex proofs, highlighting logical fallacies, and providing corrected mathematical structures in LaTeX. Examples include validating quantum mechanics equations and correcting algorithmic complexity proofs.",
      icon: BrainCircuit
    },
    { 
      id: "rlhf-detail", 
      title: "RLHF Support", 
      desc: "Reinforcement Learning from Human Feedback tailored to mathematical correctness, alignment, and STEM context.",
      details: "We build custom reward models based on thousands of pairwise comparisons generated by PhD-level annotators. We focus on penalizing plausible but incorrect reasoning steps ('reward hacking') in complex domains.",
      icon: ThumbsUp
    },
    { 
      id: "proofing-detail", 
      title: "Mathematical Proofing", 
      desc: "Deconstruction and verification of abstract mathematics, formal proofs, and algorithmic problem solving.",
      details: "Translating informal mathematics into formal language, verifying logic steps using theorem provers, and generating adversarial examples to stress-test model capabilities in pure mathematics.",
      icon: CheckSquare
    }
  ];

  const dataServices = [
    { 
      id: "synthetic-detail", 
      title: "Synthetic Data Seeds", 
      desc: "Creation of ultra-specific seed prompts and answers to bootstrap synthetic data engines across research domains.",
      details: "We produce highly diverse, highly complex seed sets covering niche subjects (e.g., condensed matter physics, bioinformatics). These seeds are used to prompt larger models to generate massive, high-variance training corpora.",
      icon: Database
    },
    { 
      id: "eval-detail", 
      title: "Evaluation Boards", 
      desc: "Adversarial testing and expert model review to prevent hallucinations in high-stakes scientific use cases.",
      details: "Comprehensive benchmarking against novel, non-public canonical datasets. We identify failure modes in multi-step reasoning, calculate pass@k metrics, and provide detailed qualitative reports on model degradation.",
      icon: Target
    },
    { 
      id: "multilingual-detail", 
      title: "Multilingual Intelligence", 
      desc: "Testing STEM reasoning logic and coding abilities applied across localized language constraints.",
      details: "Ensuring that complex scientific terminology and syntactic structures are accurately represented across languages, preserving the underlying mathematical truth without cultural or linguistic hallucination.",
      icon: Globe
    }
  ];

  const toggleExpand = (id: string) => {
    setExpandedId(prev => prev === id ? null : id);
  };

  const allServices = [
    {
      id: "reasoning",
      category: "Training Workflow",
      title: "Reasoning Verification",
      slug: "Structuring multi-step logic paths",
      desc: "Scientific experts structure logic paths for LLMs to learn optimal reasoning patterns across physical sciences and abstract physics, eliminating mathematical hallucinations.",
      icon: BrainCircuit,
      image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=1200"
    },
    {
      id: "rlhf",
      category: "Training Workflow",
      title: "RLHF Support",
      slug: "Contextual alignment & correctness",
      desc: "Reinforcement Learning from Human Feedback tailored to mathematical correctness, alignment, business logic and STEM context. Reviewers rigorously rank models on logical rigor.",
      icon: ThumbsUp,
      image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200"
    },
    {
      id: "proofing",
      category: "Training Workflow",
      title: "Mathematical Proofing",
      slug: "Formal proofs & theorem validation",
      desc: "Deconstruction and verification of abstract mathematics, formal proofs, and algorithmic problem-solving by experts fluent in Lean, LaTeX, and Mathematica.",
      icon: CheckSquare,
      image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=1200"
    },
    {
      id: "synthetic",
      category: "Data & Evaluation",
      title: "Synthetic Data Seeds",
      slug: "High-quality inputs for bootstrapping",
      desc: "Creation of ultra-specific seed prompts and answers to bootstrap synthetic data engines across research domains, enabling generalized scaling.",
      icon: Database,
      image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=1200"
    },
    {
      id: "eval",
      category: "Data & Evaluation",
      title: "Evaluation Boards",
      slug: "Adversarial testing & benchmarking",
      desc: "Adversarial testing and expert model review to prevent hallucinations in high-stakes scientific use cases utilizing novel, non-public canonical datasets.",
      icon: Target,
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=1200"
    },
    {
      id: "multilingual",
      category: "Data & Evaluation",
      title: "Multilingual Logic",
      slug: "Semantic preservation across languages",
      desc: "Testing STEM reasoning logic and coding abilities applied across localized language constraints to ensure complex scientific structures are culturally and linguistically preserved.",
      icon: Globe,
      image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=1200"
    }
  ];

  return (
    <PageTransition>
      {/* Hero Section */}
      <section className="min-h-screen pt-40 pb-24 px-6 relative flex items-center overflow-hidden">
        <DepthElement offset={20} className="absolute inset-0 pointer-events-none">
          <div className="absolute inset-0 bg-grid-pattern opacity-30" />
        </DepthElement>
        <div className="absolute right-0 top-1/4 w-[40rem] h-[40rem] bg-[var(--accent)] opacity-[0.03] rounded-full blur-[120px] pointer-events-none" />
        
        <div className="max-w-7xl mx-auto w-full relative z-10">
          <AnimatedSection className="max-w-5xl">
            <p className="inline-block px-4 py-1.5 rounded-full border border-subtle text-xs font-bold tracking-[0.2em] uppercase mb-8 text-[var(--accent)] bg-[var(--bg-secondary)]">Operations & Workflows</p>
            <h1 className="text-5xl md:text-7xl lg:text-8xl font-serif font-light tracking-tight text-primary leading-[1.1]">
              Engineered <br />
              <span className="font-sans font-semibold text-[var(--accent)] not-italic tracking-normal">precision.</span>
            </h1>
            <p className="mt-8 text-xl md:text-2xl text-secondary font-light max-w-2xl leading-relaxed">
              Minimal noise, maximum signal. We deploy PhD-level experts to construct datasets and evaluate reasoning loops at the bleeding edge.
            </p>
          </AnimatedSection>
        </div>
      </section>

      {/* Featured visual services section */}
      <section className="py-24 px-6 relative bg-secondary border-y border-subtle">
        <div className="max-w-7xl mx-auto space-y-40">
          {allServices.map((service, index) => {
            const isEven = index % 2 === 0;
            return (
              <ServiceBlock key={service.id} service={service} isEven={isEven} index={index + 1} />
            );
          })}
        </div>
      </section>

      {/* Accordion Detail list section */}
      <section className="py-32 px-6 relative overflow-hidden bg-[var(--bg-primary)]">
        <div className="max-w-7xl mx-auto relative z-10">
          <AnimatedSection className="mb-20 text-center max-w-3xl mx-auto">
            <h2 className="text-4xl md:text-5xl font-serif font-light text-primary mb-6">Capabilities Deep-Dive</h2>
            <p className="text-xl text-secondary font-light">Explore specific workflows and operational details for our core scientific annotation domains.</p>
          </AnimatedSection>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 lg:gap-24">
            {/* Column 1 */}
            <div className="relative">
              <AnimatedSection>
                <div className="mb-12 border-b border-subtle pb-6 flex items-center justify-between">
                  <h2 className="text-2xl lg:text-3xl font-serif italic tracking-wide text-primary">Training Workflows</h2>
                  <span className="text-[10px] uppercase font-bold tracking-widest text-secondary opacity-50">01</span>
                </div>
              </AnimatedSection>
              
              <AnimatedSection staggerChildren>
                <div className="flex flex-col gap-6">
                  {trainingServices.map((service) => {
                    const isExpanded = expandedId === service.id;
                    return (
                      <AnimatedItem key={service.id} className="group relative">
                        <div 
                          className={`
                            border border-subtle bg-[#FFFFFF]/50 dark:bg-[#111111]/50 rounded-[32px] p-8 
                            hover:border-[var(--accent)] transition-all cursor-pointer relative overflow-hidden
                            ${isExpanded ? 'border-[var(--accent)] shadow-md bg-[var(--bg-secondary)]' : 'shadow-sm'}
                          `}
                          onClick={() => toggleExpand(service.id)}
                        >
                          <div className={`absolute inset-0 bg-gradient-to-br from-[var(--accent)] to-transparent opacity-0 transition-opacity duration-500 pointer-events-none ${isExpanded ? 'opacity-5' : 'group-hover:opacity-[0.02]'}`} />
                          
                          <div className="flex justify-between items-start gap-5">
                            <div className="flex flex-col sm:flex-row gap-5">
                              <div className="shrink-0 w-12 h-12 flex items-center justify-center rounded-2xl bg-primary border border-subtle group-hover:border-[var(--accent)] transition-colors">
                                <service.icon className="w-6 h-6 text-[var(--accent)]" />
                              </div>
                              <div>
                                <div className="absolute -left-0 top-1/2 -translate-y-1/2 w-1 h-0 bg-[var(--accent)] rounded-r-full opacity-0 transition-all duration-300 group-hover:h-8 group-hover:opacity-100" />
                                <h3 className="text-lg md:text-xl font-medium tracking-tight mb-2 text-primary transition-colors">{service.title}</h3>
                                <p className="text-secondary leading-relaxed text-sm pr-4">{service.desc}</p>
                              </div>
                            </div>
                            <button 
                              className={`shrink-0 flex items-center justify-center gap-2 px-4 h-10 rounded-full border border-subtle bg-primary text-primary transition-colors group-hover:border-[var(--accent)] group-hover:text-[var(--accent)] text-sm font-medium mt-2 sm:mt-0`}
                              aria-expanded={isExpanded}
                            >
                              Learn More
                              <motion.div animate={{ rotate: isExpanded ? 180 : 0 }} transition={{ duration: 0.3, ease: 'easeInOut' }}>
                                <ChevronDown className="w-4 h-4" />
                              </motion.div>
                            </button>
                          </div>

                          <AnimatePresence>
                            {isExpanded && (
                              <motion.div
                                initial={{ height: 0, opacity: 0, marginTop: 0 }}
                                animate={{ height: 'auto', opacity: 1, marginTop: 24 }}
                                exit={{ height: 0, opacity: 0, marginTop: 0 }}
                                transition={{ duration: 0.3, ease: 'easeInOut' }}
                                className="overflow-hidden"
                              >
                                <div className="p-6 bg-primary rounded-2xl border border-subtle ml-2 shadow-inner">
                                  <p className="text-sm font-medium tracking-wide text-primary mb-2">Extended Workflow Details</p>
                                  <p className="text-secondary leading-relaxed text-sm">{service.details}</p>
                                </div>
                              </motion.div>
                            )}
                          </AnimatePresence>
                        </div>
                      </AnimatedItem>
                    );
                  })}
                </div>
              </AnimatedSection>
            </div>

            {/* Column 2 */}
            <div className="relative">
              <AnimatedSection>
                <div className="mb-12 border-b border-subtle pb-6 flex items-center justify-between">
                  <h2 className="text-2xl lg:text-3xl font-serif italic tracking-wide text-primary">Data & Evaluation</h2>
                  <span className="text-[10px] uppercase font-bold tracking-widest text-secondary opacity-50">02</span>
                </div>
              </AnimatedSection>

              <AnimatedSection staggerChildren>
                <div className="flex flex-col gap-6">
                  {dataServices.map((service) => {
                    const isExpanded = expandedId === service.id;
                    return (
                      <AnimatedItem key={service.id} className="group relative">
                        <div 
                          className={`
                            border border-subtle bg-[#FFFFFF]/50 dark:bg-[#111111]/50 rounded-[32px] p-8 
                            hover:border-blue-500 transition-all cursor-pointer relative overflow-hidden
                            ${isExpanded ? 'border-blue-500 shadow-md bg-[var(--bg-secondary)]' : 'shadow-sm'}
                          `}
                          onClick={() => toggleExpand(service.id)}
                        >
                          <div className={`absolute inset-0 bg-gradient-to-br from-blue-500 to-transparent opacity-0 transition-opacity duration-500 pointer-events-none ${isExpanded ? 'opacity-5' : 'group-hover:opacity-[0.02]'}`} />
                          
                          <div className="flex justify-between items-start gap-5">
                            <div className="flex flex-col sm:flex-row gap-5">
                              <div className="shrink-0 w-12 h-12 flex items-center justify-center rounded-2xl bg-primary border border-subtle group-hover:border-blue-500 transition-colors">
                                <service.icon className="w-6 h-6 text-blue-500" />
                              </div>
                              <div>
                                <div className="absolute -left-0 top-1/2 -translate-y-1/2 w-1 h-0 bg-blue-500 rounded-r-full opacity-0 transition-all duration-300 group-hover:h-8 group-hover:opacity-100" />
                                <h3 className="text-lg md:text-xl font-medium tracking-tight mb-2 text-primary transition-colors">{service.title}</h3>
                                <p className="text-secondary leading-relaxed text-sm pr-4">{service.desc}</p>
                              </div>
                            </div>
                            <button 
                              className={`shrink-0 flex items-center justify-center gap-2 px-4 h-10 rounded-full border border-subtle bg-primary text-primary transition-colors group-hover:border-blue-500 group-hover:text-blue-500 text-sm font-medium mt-2 sm:mt-0`}
                              aria-expanded={isExpanded}
                            >
                              Learn More
                              <motion.div animate={{ rotate: isExpanded ? 180 : 0 }} transition={{ duration: 0.3, ease: 'easeInOut' }}>
                                <ChevronDown className="w-4 h-4" />
                              </motion.div>
                            </button>
                          </div>

                          <AnimatePresence>
                            {isExpanded && (
                              <motion.div
                                initial={{ height: 0, opacity: 0, marginTop: 0 }}
                                animate={{ height: 'auto', opacity: 1, marginTop: 24 }}
                                exit={{ height: 0, opacity: 0, marginTop: 0 }}
                                transition={{ duration: 0.3, ease: 'easeInOut' }}
                                className="overflow-hidden"
                              >
                                <div className="p-6 bg-primary rounded-2xl border border-subtle ml-2 shadow-inner">
                                  <p className="text-sm font-medium tracking-wide text-primary mb-2">Extended Workflow Details</p>
                                  <p className="text-secondary leading-relaxed text-sm">{service.details}</p>
                                </div>
                              </motion.div>
                            )}
                          </AnimatePresence>
                        </div>
                      </AnimatedItem>
                    );
                  })}
                </div>
              </AnimatedSection>
            </div>
          </div>
        </div>
      </section>
      
      <section className="py-40 px-6 overflow-hidden bg-[var(--bg-secondary)] relative border-t border-subtle">
        <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1200')] bg-cover bg-center opacity-[0.03] mix-blend-luminosity pointer-events-none"/>
        <div className="max-w-5xl mx-auto text-center relative z-10">
            <AnimatedSection>
               <h2 className="text-4xl md:text-6xl font-serif text-primary font-light mb-8">
                 Why Specialized Domains <span className="font-sans font-semibold text-[var(--accent)] tracking-tight">Matter</span>
               </h2>
               <p className="text-xl md:text-2xl text-secondary leading-relaxed font-light max-w-3xl mx-auto mb-16">
                 General crowdsourced intelligence plateaus when verifying code, logic, or abstract mathematics. To push boundaries, your validation layer must match the complexity of the domain.
               </p>
            </AnimatedSection>
            <AnimatedSection delay={0.2} className="grid grid-cols-1 md:grid-cols-2 gap-10 text-left">
               <div className="p-10 border border-subtle rounded-[32px] bg-[#FDFCFB]/80 dark:bg-[#0A0A0A]/80 backdrop-blur-sm shadow-xl">
                  <h3 className="text-xl font-semibold mb-4 text-primary">High-Signal Data Output</h3>
                  <p className="text-secondary leading-relaxed">
                     We deliver JSONL datasets, structured markdown, and formal LaTeX annotations directly compatible with advanced fine-tuning pipelines. Zero formatting friction.
                  </p>
               </div>
               <div className="p-10 border border-subtle rounded-[32px] bg-[#FDFCFB]/80 dark:bg-[#0A0A0A]/80 backdrop-blur-sm shadow-xl">
                  <h3 className="text-xl font-semibold mb-4 text-primary">Dedicated Project Leads</h3>
                  <p className="text-secondary leading-relaxed">
                     Every enterprise operation receives a scientifically literate project manager to oversee guidelines, rubric creation, and quality assurance SLA adherence.
                  </p>
               </div>
            </AnimatedSection>
        </div>
      </section>
    </PageTransition>
  );
}

function ServiceBlock({ service, isEven, index }: { service: any, isEven: boolean, index: number }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start end", "end start"]
  });

  // Simple direct parallax
  const scaleImage = useTransform(scrollYProgress, [0, 1], [1.1, 1]);
  const yImage = useTransform(scrollYProgress, [0, 1], ["-10%", "10%"]);
  
  return (
    <AnimatedSection>
      <div 
        ref={containerRef}
        className={`flex flex-col ${isEven ? 'lg:flex-row' : 'lg:flex-row-reverse'} items-center gap-16 lg:gap-24`}
      >
        <div className="flex-1 w-full mt-4 lg:mt-0 relative h-[400px] lg:h-[600px] rounded-[40px] overflow-hidden border border-subtle bg-primary shadow-2xl group cursor-pointer">
           <motion.div 
             style={{ y: yImage, scale: scaleImage }}
             className="absolute -top-[20%] -bottom-[20%] left-0 right-0 w-full"
           >
             <img 
               src={service.image} 
               alt={service.title}
               className="w-full h-full object-cover filter grayscale mix-blend-multiply dark:mix-blend-lighten opacity-80 group-hover:grayscale-0 group-hover:mix-blend-normal group-hover:opacity-100 transition-all duration-700 ease-out group-hover:scale-105"
             />
           </motion.div>
           <div className="absolute inset-x-0 bottom-0 top-[60%] bg-gradient-to-t from-[var(--bg-secondary)] to-transparent opacity-80 mix-blend-normal pointer-events-none transition-opacity duration-700 group-hover:opacity-0" />
           <div className="absolute inset-0 shadow-[inset_0_0_100px_rgba(0,0,0,0.1)] pointer-events-none transition-opacity duration-700 group-hover:opacity-0" />
        </div>

        <div className="flex-1 w-full flex flex-col justify-center py-10 z-10">
           <div className="flex items-center gap-4 mb-8">
             <div className="w-12 h-12 rounded-2xl flex items-center justify-center bg-primary border border-subtle text-[var(--accent)] shadow-sm">
                <service.icon className="w-5 h-5" />
             </div>
             <p className="text-sm font-bold tracking-[0.2em] uppercase text-secondary">0{index} / {service.category}</p>
           </div>
           
           <h3 className="text-4xl md:text-5xl lg:text-6xl font-serif text-primary font-light mb-6 leading-tight">
             {service.title}
           </h3>
           <p className="text-xl lg:text-2xl font-serif italic text-primary/70 mb-8 border-l-4 border-[var(--accent)] pl-6">
             {service.slug}
           </p>
           <p className="text-lg text-secondary leading-relaxed font-light">
             {service.desc}
           </p>
        </div>
      </div>
    </AnimatedSection>
  );
}
