import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Search, Filter, Briefcase, MapPin, Clock, ArrowRight, Building2, PlusCircle } from 'lucide-react';
import { AnimatedSection } from './AnimatedSection';
import { Link } from 'react-router-dom';

const MOCK_JOBS = [
  {
    id: 1,
    title: 'Senior Computational Biologist',
    company: 'GeneSys AI',
    category: 'Biological Sciences',
    location: 'Remote (US/EU)',
    type: 'Contract',
    description: 'Looking for a PhD-level expert to annotate genomic sequence datasets and evaluate model predictions for structural biology.',
    salary: '$120 - $150 / hr'
  },
  {
    id: 2,
    title: 'Mathematical Proof Verifier',
    company: 'Foundation Models Lab',
    category: 'Mathematics',
    location: 'Remote',
    type: 'Milestone-based',
    description: 'Seeking experts in algebraic geometry and topology to verify multi-step formal proofs generated by a frontier LLM.',
    salary: '$5k - $10k per project'
  },
  {
    id: 3,
    title: 'Quantum Computing Data Scientist',
    company: 'Q-State Technologies',
    category: 'Physics & Cosmology',
    location: 'Hybrid (London)',
    type: 'Full-time',
    description: 'Help build the next generation of reinforcement learning environments for quantum circuit optimization.',
    salary: '£120k - £160k'
  },
  {
    id: 4,
    title: 'AI Systems Architect Consultant',
    company: 'Nexus Engineering',
    category: 'Computer Science',
    location: 'Remote',
    type: 'Contract',
    description: 'Review and refine system architecture logic generated by AI for distributed computing platforms.',
    salary: '$150 - $200 / hr'
  },
  {
    id: 5,
    title: 'Materials Science Annotator',
    company: 'ChemAI',
    category: 'Chemistry & Materials',
    location: 'Remote',
    type: 'Part-time',
    description: 'Annotate and structure datasets related to crystallography and novel material synthesis.',
    salary: '$90 - $130 / hr'
  }
];

const CATEGORIES = ['All', 'Mathematics', 'Computer Science', 'Biological Sciences', 'Physics & Cosmology', 'Chemistry & Materials', 'Engineering'];

export function JobBoard() {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState('All');
  
  const filteredJobs = useMemo(() => {
    return MOCK_JOBS.filter((job) => {
      const matchesSearch = job.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
                            job.company.toLowerCase().includes(searchQuery.toLowerCase()) ||
                            job.description.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesCategory = activeCategory === 'All' || job.category === activeCategory;
      return matchesSearch && matchesCategory;
    });
  }, [searchQuery, activeCategory]);

  return (
    <section className="py-32 px-6 bg-secondary border-t border-subtle relative overflow-hidden">
      <div className="absolute inset-0 bg-grid-pattern opacity-10 pointer-events-none" />
      
      <div className="max-w-7xl mx-auto relative z-10">
        <AnimatedSection className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-[var(--accent)] bg-[var(--accent)]/10 mb-6">
            <span className="text-xs font-mono uppercase tracking-widest text-[var(--accent)] font-bold">Network Opportunities</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-sans font-medium tracking-tight text-primary mb-6">Expert Job Board</h2>
          <p className="text-xl text-secondary leading-relaxed font-light mb-8">
            Exclusive opportunities for verified network members. Companies can source specialized talent for complex AI training operations.
          </p>
          <div className="flex justify-center gap-4">
            <Link to="/contact" className="inline-flex items-center gap-2 bg-[var(--bg-primary)] text-[var(--text-primary)] border border-subtle px-6 py-3 rounded-full font-medium hover:border-[var(--accent)] hover:text-[var(--accent)] transition-all text-sm shadow-sm">
              <PlusCircle className="w-4 h-4" />
              Post an Opportunity
            </Link>
          </div>
        </AnimatedSection>

        {/* Filters and Search */}
        <AnimatedSection className="mb-12">
          <div className="flex flex-col md:flex-row gap-6 items-center justify-between bg-primary p-4 rounded-3xl border border-subtle shadow-sm">
            <div className="relative w-full md:w-96">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-secondary opacity-50" />
              <input 
                type="text" 
                placeholder="Search precise roles or companies..." 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full bg-[var(--bg-secondary)] border border-subtle text-primary text-sm rounded-full pl-12 pr-4 py-3 outline-none focus:border-[var(--accent)] transition-colors"
              />
            </div>
            
            <div className="w-full md:w-auto overflow-x-auto pb-2 md:pb-0 hide-scrollbar">
              <div className="flex gap-2">
                {CATEGORIES.map(category => (
                  <button
                    key={category}
                    onClick={() => setActiveCategory(category)}
                    className={`whitespace-nowrap px-4 py-2 rounded-full text-xs font-medium transition-all ${
                      activeCategory === category 
                        ? 'bg-[var(--accent)] text-white' 
                        : 'bg-[var(--bg-secondary)] text-secondary border border-subtle hover:border-[var(--accent)] hover:text-primary'
                    }`}
                  >
                    {category}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </AnimatedSection>

        {/* Job Listings */}
        <div className="space-y-4">
          <AnimatePresence>
            {filteredJobs.length > 0 ? (
              filteredJobs.map((job, index) => (
                <motion.div
                  key={job.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  transition={{ duration: 0.3, delay: index * 0.05 }}
                  className="bg-primary border border-subtle rounded-3xl p-6 md:p-8 hover:border-[var(--accent)]/50 transition-all group shadow-sm flex flex-col md:flex-row gap-6 md:gap-8 justify-between items-start md:items-center"
                >
                  <div className="flex-1">
                    <div className="flex flex-wrap items-center gap-3 mb-3">
                      <span className="text-[10px] font-mono tracking-wider text-[var(--accent)] px-3 py-1 rounded-full bg-[var(--accent)]/10 border border-[var(--accent)]/20">
                        {job.category}
                      </span>
                      <span className="text-[10px] font-bold uppercase tracking-wider text-secondary px-3 py-1 rounded-full bg-[var(--bg-secondary)] border border-subtle flex items-center gap-1.5">
                        <Clock className="w-3 h-3" /> {job.type}
                      </span>
                      <span className="text-[10px] font-bold uppercase tracking-wider text-secondary px-3 py-1 rounded-full bg-[var(--bg-secondary)] border border-subtle flex items-center gap-1.5">
                        <MapPin className="w-3 h-3" /> {job.location}
                      </span>
                    </div>
                    
                    <h3 className="text-2xl font-serif text-primary mb-2 group-hover:text-[var(--accent)] transition-colors">{job.title}</h3>
                    
                    <div className="flex items-center gap-2 text-sm text-secondary mb-4">
                      <Building2 className="w-4 h-4 opacity-70" />
                      <span className="font-medium">{job.company}</span>
                    </div>
                    
                    <p className="text-secondary font-light text-sm md:text-base leading-relaxed max-w-3xl">
                      {job.description}
                    </p>
                  </div>
                  
                  <div className="flex flex-col items-start md:items-end w-full md:w-auto gap-4 md:border-l md:border-subtle md:pl-8 py-2">
                    <div className="text-left md:text-right">
                      <p className="text-[10px] uppercase tracking-widest text-secondary font-bold mb-1">Compensation</p>
                      <p className="text-lg font-mono text-primary">{job.salary}</p>
                    </div>
                    <Link to="/contact" className="w-full md:w-auto bg-[var(--text-primary)] text-[var(--bg-primary)] px-6 py-3 rounded-xl text-sm font-bold uppercase tracking-widest hover:opacity-90 transition-opacity flex items-center justify-center gap-2 group-hover:bg-[var(--accent)] group-hover:text-white">
                      Apply Now <ArrowRight className="w-4 h-4 -translate-x-2 opacity-0 group-hover:translate-x-0 group-hover:opacity-100 transition-all" />
                    </Link>
                  </div>
                </motion.div>
              ))
            ) : (
              <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="text-center py-20 bg-primary border border-subtle rounded-3xl"
              >
                <Briefcase className="w-12 h-12 text-secondary opacity-30 mx-auto mb-4" />
                <h3 className="text-xl font-medium text-primary mb-2">No matching opportunities found</h3>
                <p className="text-secondary font-light">Try adjusting your search criteria or modifying your filters.</p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </section>
  );
}
